CREATE TABLE phonebook(
    phonebook_id int GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    first_name VARCHAR(30),
    last_name VARCHAR(30),
    three_name VARCHAR(30),
    number_phone VARCHAR(30),
    address VARCHAR(30),
    description VARCHAR(30),
    CONSTRAINT pk_phonebook PRIMARY KEY (phonebook_id)
);

INSERT INTO phonebook (last_name, first_name, three_name, number_phone, address, description)
VALUES
    ('Иванов', 'Иван', 'Иванович','+7(919)154-56-78', 'ул. Ленина 1, 15', 'рабочий'),
    ('Петров', 'Пётр', 'Петрович','+7(919)154-56-79', 'ул. Петрова 7, 3', 'рабочий'),
    ('Сидоров', 'Сидор', 'Сидорович', '+7(919)154-56-80', 'ул. Пушкина 4, 1', 'рабочий')